// priority: 999999

global.StrippedLumber = {
  logs: [
    'aether_redux:stripped_blightwillow_log',
    'aether_redux:stripped_cloudcap_stem',
    'aether_redux:stripped_crystal_log',
    'aether_redux:stripped_fieldsprout_log',
    'aether_redux:stripped_glacia_log',
    'aether:stripped_skyroot_log',
    'deep_aether:stripped_conberry_log',
    'deep_aether:stripped_cruderoot_log',
    'deep_aether:stripped_roseroot_log',
    'deep_aether:stripped_sunroot_log',
    'deep_aether:stripped_yagroot_log',
    'eidolon:stripped_illwood_log',
    'regions_unexplored:stripped_baobab_log',
    'regions_unexplored:stripped_blackwood_log',
    'regions_unexplored:stripped_brimwood_log',
    'regions_unexplored:stripped_cobalt_log',
    'regions_unexplored:stripped_cypress_log',
    'regions_unexplored:stripped_dead_log',
    'regions_unexplored:stripped_eucalyptus_log',
    'regions_unexplored:stripped_joshua_log',
    'regions_unexplored:stripped_kapok_log',
    'regions_unexplored:stripped_larch_log',
    'regions_unexplored:stripped_magnolia_log',
    'regions_unexplored:stripped_maple_log',
    'regions_unexplored:stripped_mauve_log',
    'regions_unexplored:stripped_palm_log',
    'regions_unexplored:stripped_pine_log',
    'regions_unexplored:stripped_redwood_log',
    'regions_unexplored:stripped_socotra_log',
    'regions_unexplored:stripped_willow_log',
  ],
  woods: [
    'aether_redux:stripped_blightwillow_wood',
    'aether_redux:stripped_cloudcap_hyphae',
    'aether_redux:stripped_crystal_wood',
    'aether_redux:stripped_fieldsprout_wood',
    'aether_redux:stripped_glacia_wood',
    'aether:stripped_skyroot_wood',
    'deep_aether:stripped_conberry_wood',
    'deep_aether:stripped_cruderoot_wood',
    'deep_aether:stripped_roseroot_wood',
    'deep_aether:stripped_sunroot_wood',
    'deep_aether:stripped_yagroot_wood',
    'eidolon:stripped_illwood_bark',
    'regions_unexplored:stripped_baobab_wood',
    'regions_unexplored:stripped_blackwood_wood',
    'regions_unexplored:stripped_brimwood_wood',
    'regions_unexplored:stripped_cobalt_wood',
    'regions_unexplored:stripped_cypress_wood',
    'regions_unexplored:stripped_dead_wood',
    'regions_unexplored:stripped_eucalyptus_wood',
    'regions_unexplored:stripped_joshua_wood',
    'regions_unexplored:stripped_kapok_wood',
    'regions_unexplored:stripped_larch_wood',
    'regions_unexplored:stripped_magnolia_wood',
    'regions_unexplored:stripped_maple_wood',
    'regions_unexplored:stripped_mauve_wood',
    'regions_unexplored:stripped_palm_wood',
    'regions_unexplored:stripped_pine_wood',
    'regions_unexplored:stripped_redwood_wood',
    'regions_unexplored:stripped_socotra_wood',
    'regions_unexplored:stripped_willow_wood',
  ],
  stems: [
    'regions_unexplored:stripped_blue_bioshroom_stem',
    'regions_unexplored:stripped_green_bioshroom_stem',
    'regions_unexplored:stripped_pink_bioshroom_stem',
    'regions_unexplored:stripped_yellow_bioshroom_stem',
  ],
  hyphae: [
    'regions_unexplored:stripped_blue_bioshroom_hyphae',
    'regions_unexplored:stripped_green_bioshroom_hyphae',
    'regions_unexplored:stripped_pink_bioshroom_hyphae',
    'regions_unexplored:stripped_yellow_bioshroom_hyphae',
  ],
};

global.Metals = {
  aluminum: {
    ingot: 'immersiveengineering:ingot_aluminum',
    block: 'immersiveengineering:storage_aluminum',
    nugget: 'immersiveengineering:nugget_aluminum',
    dust: 'immersiveengineering:dust_aluminum',
    crushed: 'create:crushed_raw_aluminum',
  },
  copper: {
    ingot: 'minecraft:copper_ingot',
    block: 'minecraft:copper_block',
    nugget: 'create:copper_nugget',
    dust: 'mekanism:dust_copper',
    crushed: 'create:crushed_raw_copper',
  },
  gold: {
    ingot: 'minecraft:gold_ingot',
    block: 'minecraft:gold_block',
    nugget: 'minecraft:gold_nugget',
    dust: 'mekanism:dust_gold',
    crushed: 'create:crushed_raw_gold',
  },
  iron: {
    ingot: 'minecraft:iron_ingot',
    block: 'minecraft:iron_block',
    nugget: 'minecraft:iron_nugget',
    dust: 'mekanism:dust_iron',
    crushed: 'create:crushed_raw_iron',
  },
  lead: {
    ingot: 'eidolon:lead_ingot',
    block: 'eidolon:lead_block',
    nugget: 'eidolon:lead_nugget',
    dust: 'mekanism:dust_lead',
    crushed: 'create:crushed_raw_lead',
  },
  nickel: {
    ingot: 'immersiveengineering:ingot_nickel',
    block: 'immersiveengineering:storage_nickel',
    nugget: 'immersiveengineering:nugget_nickel',
    dust: 'immersiveengineering:dust_nickel',
    crushed: 'create:crushed_raw_nickel',
  },
  silver: {
    ingot: 'eidolon:silver_ingot',
    block: 'eidolon:silver_block',
    nugget: 'eidolon:silver_nugget',
    dust: 'immersiveengineering:dust_silver',
    crushed: 'create:crushed_raw_silver',
  },
  tin: {
    ingot: 'mekanism:ingot_tin',
    block: 'mekanism:block_tin',
    nugget: 'mekanism:nugget_tin',
    dust: 'mekanism:dust_tin',
    crushed: 'create:crushed_raw_tin',
  },
  uranium: {
    ingot: 'mekanism:ingot_uranium',
    block: 'mekanism:block_uranium',
    nugget: 'mekanism:nugget_uranium',
    dust: 'mekanism:dust_uranium',
    crushed: 'create:crushed_raw_uranium',
  },
  zinc: {
    ingot: 'create:zinc_ingot',
    block: 'create:zinc_block',
    nugget: 'create:zinc_nugget',
    dust: 'create:crushed_raw_zinc',
    crushed: 'create:crushed_raw_zinc',
  },
};
