// priority: 999999

global.StrippedLumber = {
  logs: [
    'aether_redux:stripped_blightwillow_log',
    'aether_redux:stripped_cloudcap_stem',
    'aether_redux:stripped_crystal_log',
    'aether_redux:stripped_fieldsprout_log',
    'aether_redux:stripped_glacia_log',
    'aether:stripped_skyroot_log',
    'deep_aether:stripped_conberry_log',
    'deep_aether:stripped_cruderoot_log',
    'deep_aether:stripped_roseroot_log',
    'deep_aether:stripped_sunroot_log',
    'deep_aether:stripped_yagroot_log',
    'eidolon:stripped_illwood_log',
    'regions_unexplored:stripped_baobab_log',
    'regions_unexplored:stripped_blackwood_log',
    'regions_unexplored:stripped_brimwood_log',
    'regions_unexplored:stripped_cobalt_log',
    'regions_unexplored:stripped_cypress_log',
    'regions_unexplored:stripped_dead_log',
    'regions_unexplored:stripped_eucalyptus_log',
    'regions_unexplored:stripped_joshua_log',
    'regions_unexplored:stripped_kapok_log',
    'regions_unexplored:stripped_larch_log',
    'regions_unexplored:stripped_magnolia_log',
    'regions_unexplored:stripped_maple_log',
    'regions_unexplored:stripped_mauve_log',
    'regions_unexplored:stripped_palm_log',
    'regions_unexplored:stripped_pine_log',
    'regions_unexplored:stripped_redwood_log',
    'regions_unexplored:stripped_socotra_log',
    'regions_unexplored:stripped_willow_log',
  ],
  woods: [
    'aether_redux:stripped_blightwillow_wood',
    'aether_redux:stripped_cloudcap_hyphae',
    'aether_redux:stripped_crystal_wood',
    'aether_redux:stripped_fieldsprout_wood',
    'aether_redux:stripped_glacia_wood',
    'aether:stripped_skyroot_wood',
    'deep_aether:stripped_conberry_wood',
    'deep_aether:stripped_cruderoot_wood',
    'deep_aether:stripped_roseroot_wood',
    'deep_aether:stripped_sunroot_wood',
    'deep_aether:stripped_yagroot_wood',
    'eidolon:stripped_illwood_bark',
    'regions_unexplored:stripped_baobab_wood',
    'regions_unexplored:stripped_blackwood_wood',
    'regions_unexplored:stripped_brimwood_wood',
    'regions_unexplored:stripped_cobalt_wood',
    'regions_unexplored:stripped_cypress_wood',
    'regions_unexplored:stripped_dead_wood',
    'regions_unexplored:stripped_eucalyptus_wood',
    'regions_unexplored:stripped_joshua_wood',
    'regions_unexplored:stripped_kapok_wood',
    'regions_unexplored:stripped_larch_wood',
    'regions_unexplored:stripped_magnolia_wood',
    'regions_unexplored:stripped_maple_wood',
    'regions_unexplored:stripped_mauve_wood',
    'regions_unexplored:stripped_palm_wood',
    'regions_unexplored:stripped_pine_wood',
    'regions_unexplored:stripped_redwood_wood',
    'regions_unexplored:stripped_socotra_wood',
    'regions_unexplored:stripped_willow_wood',
  ],
  stems: [
    'regions_unexplored:stripped_blue_bioshroom_stem',
    'regions_unexplored:stripped_green_bioshroom_stem',
    'regions_unexplored:stripped_pink_bioshroom_stem',
    'regions_unexplored:stripped_yellow_bioshroom_stem',
  ],
  hyphae: [
    'regions_unexplored:stripped_blue_bioshroom_hyphae',
    'regions_unexplored:stripped_green_bioshroom_hyphae',
    'regions_unexplored:stripped_pink_bioshroom_hyphae',
    'regions_unexplored:stripped_yellow_bioshroom_hyphae',
  ],
};

global.Metals = {
  aluminum: {
    ingot: 'immersiveengineering:ingot_aluminum',
    block: 'immersiveengineering:storage_aluminum',
    nugget: 'immersiveengineering:nugget_aluminum',
    dust: 'immersiveengineering:dust_aluminum',
    crushed: 'create:crushed_raw_aluminum',
  },
  copper: {
    ingot: 'minecraft:copper_ingot',
    block: 'minecraft:copper_block',
    nugget: 'create:copper_nugget',
    dust: 'mekanism:dust_copper',
    crushed: 'create:crushed_raw_copper',
  },
  gold: {
    ingot: 'minecraft:gold_ingot',
    block: 'minecraft:gold_block',
    nugget: 'minecraft:gold_nugget',
    dust: 'mekanism:dust_gold',
    crushed: 'create:crushed_raw_gold',
  },
  iron: {
    ingot: 'minecraft:iron_ingot',
    block: 'minecraft:iron_block',
    nugget: 'minecraft:iron_nugget',
    dust: 'mekanism:dust_iron',
    crushed: 'create:crushed_raw_iron',
  },
  lead: {
    ingot: 'eidolon:lead_ingot',
    block: 'eidolon:lead_block',
    nugget: 'eidolon:lead_nugget',
    dust: 'mekanism:dust_lead',
    crushed: 'create:crushed_raw_lead',
  },
  nickel: {
    ingot: 'immersiveengineering:ingot_nickel',
    block: 'immersiveengineering:storage_nickel',
    nugget: 'immersiveengineering:nugget_nickel',
    dust: 'immersiveengineering:dust_nickel',
    crushed: 'create:crushed_raw_nickel',
  },
  silver: {
    ingot: 'eidolon:silver_ingot',
    block: 'eidolon:silver_block',
    nugget: 'eidolon:silver_nugget',
    dust: 'immersiveengineering:dust_silver',
    crushed: 'create:crushed_raw_silver',
  },
  tin: {
    ingot: 'mekanism:ingot_tin',
    block: 'mekanism:block_tin',
    nugget: 'mekanism:nugget_tin',
    dust: 'mekanism:dust_tin',
    crushed: 'create:crushed_raw_tin',
  },
  uranium: {
    ingot: 'mekanism:ingot_uranium',
    block: 'mekanism:block_uranium',
    nugget: 'mekanism:nugget_uranium',
    dust: 'mekanism:dust_uranium',
    crushed: 'create:crushed_raw_uranium',
  },
  zinc: {
    ingot: 'create:zinc_ingot',
    block: 'create:zinc_block',
    nugget: 'create:zinc_nugget',
    dust: 'kubejs:zinc_dust',
    crushed: 'create:crushed_raw_zinc',
  },
};

global.Stages = {
  aether: {
    mods: ['aether', 'aether_redux', 'deep_aether'],
    substitute: Item.of('kubejs:unknown_holy_item'),
    exceptions: Ingredient.of([
      'aether:leather_gloves',
      'aether:chainmail_gloves',
      'aether:iron_gloves',
      'aether:golden_gloves',
      'aether:diamond_gloves',
      'aether:netherite_gloves',
    ]),
  },
  bloodmagic: {
    mods: ['bloodmagic'],
    substitute: Item.of('kubejs:unknown_bloody_item'),
    exceptions: null,
  },
  embers: {
    mods: ['embers'],
    substitute: Item.of('kubejs:unknown_dwarven_item'),
    exceptions: Ingredient.of([
      '#forge:ingots/archaic_brick',
      '#forge:ores/lead',
      '#forge:ores/silver',
      'embers:lead_axe',
      'embers:lead_hoe',
      'embers:lead_pickaxe',
      'embers:lead_shovel',
      'embers:lead_sword'
    ]),
  },
  create: {
    mods: ['create', 'railways', 'create_power_loader', 'prettypipes'],
    substitute: Item.of('kubejs:unknown_kinetic_item'),
    exceptions: Ingredient.of('#create:exception'),
  },
  pnc: {
    mods: ['pneumaticcraft'],
    substitute: Item.of('kubejs:unknown_pneumatic_item'),
    exceptions: Ingredient.of('#pneumaticcraft:exception'),
  },
  ie: {
    mods: ['immersiveengineering', 'buildinggadgets2'],
    substitute: Item.of('kubejs:unknown_engineering_item'),
    exceptions: Ingredient.of('#immersiveengineering:exception'),
  },
  mekanism: {
    mods: ['mekanism', 'mekanismgenerators', 'mekaweapons', 'dimstorage', 'rftoolsbase', 'xnet'],
    substitute: Item.of('kubejs:unknown_electric_item'),
    exceptions: Ingredient.of('#mekanism:exception'),
  },
  ae2: {
    mods: ['ae2', 'appmek', 'more_immersive_wires', 'specialised_cells', 'ae2wtlib', 'aeinfinitybooster', 'merequester', 'entangled'],
    substitute: Item.of('kubejs:unknown_energistic_item'),
    exceptions: Ingredient.of('#ae2:exception'),
  },
};

global.Tools = {
  /* Gearset Order: Sword, Pick, Shovel, Axe, Hoe */
  base: [
    {
      type: 'wood',
      next: ['stone'],
      items: [
        { item: 'minecraft:wooden_sword', material: '#minecraft:planks' },
        { item: 'minecraft:wooden_pickaxe', material: '#minecraft:planks' },
        { item: 'minecraft:wooden_shovel', material: '#minecraft:planks' },
        { item: 'minecraft:wooden_axe', material: '#minecraft:planks' },
        { item: 'minecraft:wooden_hoe', material: '#minecraft:planks' },
      ],
    },
    {
      type: 'stone',
      next: ['iron', 'silver', 'lead', 'certus', 'quartz'],
      items: [
        { item: 'minecraft:stone_sword', material: '#minecraft:stone_tool_materials' },
        { item: 'minecraft:stone_pickaxe', material: '#minecraft:stone_tool_materials' },
        { item: 'minecraft:stone_shovel', material: '#minecraft:stone_tool_materials' },
        { item: 'minecraft:stone_axe', material: '#minecraft:stone_tool_materials' },
        { item: 'minecraft:stone_hoe', material: '#minecraft:stone_tool_materials' },
      ],
    },
    {
      type: 'iron',
      next: ['steel', 'dawnstone', 'gold'],
      items: [
        { item: 'minecraft:iron_sword', material: '#forge:ingots/iron' },
        { item: 'minecraft:iron_pickaxe', material: '#forge:ingots/iron' },
        { item: 'minecraft:iron_shovel', material: '#forge:ingots/iron' },
        { item: 'minecraft:iron_axe', material: '#forge:ingots/iron' },
        { item: 'minecraft:iron_hoe', material: '#forge:ingots/iron' },
      ],
    },
    {
      type: 'silver',
      next: [],
      items: [
        { item: 'eidolon:silver_sword', material: '#forge:ingots/silver' },
        { item: 'eidolon:silver_pickaxe', material: '#forge:ingots/silver' },
        { item: 'eidolon:silver_shovel', material: '#forge:ingots/silver' },
        { item: 'eidolon:silver_axe', material: '#forge:ingots/silver' },
        { item: 'eidolon:silver_hoe', material: '#forge:ingots/silver' },
      ],
    },
    {
      type: 'lead',
      next: [],
      items: [
        { item: 'embers:lead_sword', material: '#forge:ingots/lead' },
        { item: 'embers:lead_pickaxe', material: '#forge:ingots/lead' },
        { item: 'embers:lead_shovel', material: '#forge:ingots/lead' },
        { item: 'embers:lead_axe', material: '#forge:ingots/lead' },
        { item: 'embers:lead_hoe', material: '#forge:ingots/lead' },
      ],
    },
    {
      type: 'certus',
      next: [],
      items: [
        { item: 'ae2:certus_quartz_sword', material: 'ae2:certus_quartz_crystal' },
        { item: 'ae2:certus_quartz_pickaxe', material: 'ae2:certus_quartz_crystal' },
        { item: 'ae2:certus_quartz_shovel', material: 'ae2:certus_quartz_crystal' },
        { item: 'ae2:certus_quartz_axe', material: 'ae2:certus_quartz_crystal' },
        { item: 'ae2:certus_quartz_hoe', material: 'ae2:certus_quartz_crystal' },
      ],
    },
    {
      type: 'quartz',
      next: [],
      items: [
        { item: 'ae2:nether_quartz_sword', material: 'minecraft:quartz' },
        { item: 'ae2:nether_quartz_pickaxe', material: 'minecraft:quartz' },
        { item: 'ae2:nether_quartz_shovel', material: 'minecraft:quartz' },
        { item: 'ae2:nether_quartz_axe', material: 'minecraft:quartz' },
        { item: 'ae2:nether_quartz_hoe', material: 'minecraft:quartz' },
      ],
    },
    {
      type: 'steel',
      next: ['diamond'],
      items: [
        { item: 'immersiveengineering:sword_steel', material: '#forge:ingots/steel' },
        { item: 'immersiveengineering:pickaxe_steel', material: '#forge:ingots/steel' },
        { item: 'immersiveengineering:shovel_steel', material: '#forge:ingots/steel' },
        { item: 'immersiveengineering:axe_steel', material: '#forge:ingots/steel' },
        { item: 'immersiveengineering:hoe_steel', material: '#forge:ingots/steel' },
      ],
    },
    {
      type: 'dawnstone',
      next: ['diamond'],
      items: [
        { item: 'embers:dawnstone_sword', material: '#forge:ingots/dawnstone' },
        { item: 'embers:dawnstone_pickaxe', material: '#forge:ingots/dawnstone' },
        { item: 'embers:dawnstone_shovel', material: '#forge:ingots/dawnstone' },
        { item: 'embers:dawnstone_axe', material: '#forge:ingots/dawnstone' },
        { item: 'embers:dawnstone_hoe', material: '#forge:ingots/dawnstone' },
      ],
    },
    {
      type: 'gold',
      next: [],
      items: [
        { item: 'minecraft:golden_sword', material: '#forge:ingots/gold' },
        { item: 'minecraft:golden_pickaxe', material: '#forge:ingots/gold' },
        { item: 'minecraft:golden_shovel', material: '#forge:ingots/gold' },
        { item: 'minecraft:golden_axe', material: '#forge:ingots/gold' },
        { item: 'minecraft:golden_hoe', material: '#forge:ingots/gold' },
      ],
    },
    {
      type: 'diamond',
      next: [],
      items: [
        { item: 'minecraft:diamond_sword', material: 'minecraft:diamond' },
        { item: 'minecraft:diamond_pickaxe', material: 'minecraft:diamond' },
        { item: 'minecraft:diamond_shovel', material: 'minecraft:diamond' },
        { item: 'minecraft:diamond_axe', material: 'minecraft:diamond' },
        { item: 'minecraft:diamond_hoe', material: 'minecraft:diamond' },
      ],
    },
  ],
  /* Gearset Order: Helmet, Chestplate, Leggings, Boots */
  armor: [
    {
      type: 'leather',
      next: ['chain'],
      items: [
        { item: 'minecraft:leather_helmet', material: 'minecraft:leather' },
        { item: 'minecraft:leather_chestplate', material: 'minecraft:leather' },
        { item: 'minecraft:leather_leggings', material: 'minecraft:leather' },
        { item: 'minecraft:leather_boots', material: 'minecraft:leather' },
      ],
    },
    {
      type: 'chain',
      next: ['iron', 'silver'],
      items: [
        { item: 'minecraft:chainmail_helmet', material: 'minecraft:chain' },
        { item: 'minecraft:chainmail_chestplate', material: 'minecraft:chain' },
        { item: 'minecraft:chainmail_leggings', material: 'minecraft:chain' },
        { item: 'minecraft:chainmail_boots', material: 'minecraft:chain' },
      ],
    },
    {
      type: 'iron',
      next: ['steel', 'gold'],
      items: [
        { item: 'minecraft:iron_helmet', material: '#forge:ingots/iron' },
        { item: 'minecraft:iron_chestplate', material: '#forge:ingots/iron' },
        { item: 'minecraft:iron_leggings', material: '#forge:ingots/iron' },
        { item: 'minecraft:iron_boots', material: '#forge:ingots/iron' },
      ],
    },
    {
      type: 'silver',
      next: [],
      items: [
        { item: 'eidolon:silver_helmet', material: '#forge:ingots/silver' },
        { item: 'eidolon:silver_chestplate', material: '#forge:ingots/silver' },
        { item: 'eidolon:silver_leggings', material: '#forge:ingots/silver' },
        { item: 'eidolon:silver_boots', material: '#forge:ingots/silver' },
      ],
    },
    {
      type: 'steel',
      next: ['diamond'],
      items: [
        { item: 'immersiveengineering:armor_steel_helmet', material: '#forge:plates/steel' },
        { item: 'immersiveengineering:armor_steel_chestplate', material: '#forge:plates/steel' },
        { item: 'immersiveengineering:armor_steel_leggings', material: '#forge:plates/steel' },
        { item: 'immersiveengineering:armor_steel_boots', material: '#forge:plates/steel' },
      ],
    },

    {
      type: 'gold',
      next: [],
      items: [
        { item: 'minecraft:golden_helmet', material: '#forge:ingots/gold' },
        { item: 'minecraft:golden_chestplate', material: '#forge:ingots/gold' },
        { item: 'minecraft:golden_leggings', material: '#forge:ingots/gold' },
        { item: 'minecraft:golden_boots', material: '#forge:ingots/gold' },
      ],
    },
    {
      type: 'diamond',
      next: [],
      items: [
        { item: 'minecraft:diamond_helmet', material: 'minecraft:diamond' },
        { item: 'minecraft:diamond_chestplate', material: 'minecraft:diamond' },
        { item: 'minecraft:diamond_leggings', material: 'minecraft:diamond' },
        { item: 'minecraft:diamond_boots', material: 'minecraft:diamond' },
      ],
    },
  ],
  gloves: [
    {
      type: 'leather',
      next: ['chain'],
      items: [{ item: 'aether:leather_gloves', material: 'minecraft:leather' }],
    },
    {
      type: 'chain',
      next: ['iron'],
      items: [{ item: 'aether:chainmail_gloves', material: 'minecraft:chain' }],
    },
    {
      type: 'iron',
      next: ['gold', 'diamond'],
      items: [{ item: 'aether:iron_gloves', material: '#forge:ingots/iron' }],
    },
    {
      type: 'gold',
      next: [],
      items: [{ item: 'aether:golden_gloves', material: '#forge:ingots/gold' }],
    },
    {
      type: 'diamond',
      next: [],
      items: [{ item: 'aether:diamond_gloves', material: 'minecraft:diamond' }],
    },
  ],
  knives: [
    {
      type: 'flint',
      next: ['iron'],
      items: [{ item: 'farmersdelight:flint_knife', material: 'minecraft:flint' }],
    },
    {
      type: 'iron',
      next: ['steel', 'silver', 'gold'],
      items: [{ item: 'farmersdelight:iron_knife', material: '#forge:ingots/iron' }],
    },
    {
      type: 'steel',
      next: ['diamond'],
      items: [{ item: 'delightful:steel_knife', material: '#forge:ingots/steel' }],
    },
    {
      type: 'silver',
      next: [],
      items: [{ item: 'delightful:silver_knife', material: '#forge:ingots/silver' }],
    },
    {
      type: 'gold',
      next: [],
      items: [{ item: 'farmersdelight:golden_knife', material: '#forge:ingots/gold' }],
    },
    {
      type: 'diamond',
      next: [],
      items: [{ item: 'farmersdelight:diamond_knife', material: 'minecraft:diamond' }],
    },
  ],
  machetes: [
    {
      type: 'iron',
      next: ['gold', 'diamond'],
      items: [{ item: 'nethersdelight:iron_machete', material: '#forge:ingots/iron' }],
    },
    {
      type: 'gold',
      next: [],
      items: [{ item: 'nethersdelight:golden_machete', material: '#forge:ingots/gold' }],
    },
    {
      type: 'diamond',
      next: [],
      items: [{ item: 'nethersdelight:diamond_machete', material: 'minecraft:diamond' }],
    },
  ]
};

global.ToolScrapBlacklist = [
  'delightful:adamantium_knife',
  'delightful:alf_knife',
  'delightful:allthemodium_knife',
  'delightful:amethyst_knife',
  'delightful:black_opal_knife',
  'delightful:blazing_knife',
  'delightful:bone_knife',
  'delightful:brass_knife',
  'delightful:bronze_knife',
  'delightful:cloggrum_knife',
  'delightful:constantan_knife',
  'delightful:copper_knife',
  'delightful:crystalline_knife',
  'delightful:draco_arcanus_knife',
  'delightful:electrum_knife',
  'delightful:elementium_knife',
  'delightful:emerald_knife',
  'delightful:enderite_knife',
  'delightful:experience_knife',
  'delightful:fiery_knife',
  'delightful:forgotten_knife',
  'delightful:froststeel_knife',
  'delightful:gilded_netherite_knife',
  'delightful:gilded_quartz_knife',
  'delightful:invar_knife',
  'delightful:ironwood_knife',
  'delightful:kiwano_knife',
  'delightful:knightmetal_knife',
  'delightful:lapis_lazuli_knife',
  'delightful:large_amethyst_knife',
  'delightful:lead_knife',
  'delightful:leaf_knife',
  'delightful:living_knife',
  'delightful:manasteel_knife',
  'delightful:mythril_knife',
  'delightful:necronium_knife',
  'delightful:netherite_opal_knife',
  'delightful:nickel_knife',
  'delightful:obsidian_infused_enderite_knife',
  'delightful:onyx_knife',
  'delightful:osmium_knife',
  'delightful:pendorite_knife',
  'delightful:refined_glowstone_knife',
  'delightful:refined_obsidian_knife',
  'delightful:rose_gold_knife',
  'delightful:sinisite_knife',
  'delightful:soul_steel_knife',
  'delightful:steeleaf_knife',
  'delightful:stellium_knife',
  'delightful:terra_knife',
  'delightful:thyrium_knife',
  'delightful:tin_knife',
  'delightful:utherium_knife',
  'delightful:warden_knife',
  'delightful:zinc_knife',
  'outer_end:cobalt_crystal_boots',
  'outer_end:cobalt_crystal_chestplate',
  'outer_end:cobalt_crystal_helmet',
  'outer_end:cobalt_crystal_leggings',
  'outer_end:mint_crystal_boots',
  'outer_end:mint_crystal_chestplate',
  'outer_end:mint_crystal_helmet',
  'outer_end:mint_crystal_leggings',
  'outer_end:rose_crystal_boots',
  'outer_end:rose_crystal_chestplate',
  'outer_end:rose_crystal_helmet',
  'outer_end:rose_crystal_leggings',
  'outer_end:sinker_dagger',
];

