// priority: 999999

global.StrippedLumber = JsonIO.read('kubejs/globals/lumber.json').stripped;

global.Metals = JsonIO.read('kubejs/globals/metals.json');

global.Stages = JsonIO.read('kubejs/globals/stages.json');

global.Tools = JsonIO.read('kubejs/globals/tools.json');

global.Colors = JsonIO.read('kubejs/globals/colors.json');

global.ToolScrapBlacklist = [
  'delightful:adamantium_knife',
  'delightful:alf_knife',
  'delightful:allthemodium_knife',
  'delightful:amethyst_knife',
  'delightful:black_opal_knife',
  'delightful:blazing_knife',
  'delightful:bone_knife',
  'delightful:brass_knife',
  'delightful:bronze_knife',
  'delightful:cloggrum_knife',
  'delightful:constantan_knife',
  'delightful:copper_knife',
  'delightful:crystalline_knife',
  'delightful:draco_arcanus_knife',
  'delightful:electrum_knife',
  'delightful:elementium_knife',
  'delightful:emerald_knife',
  'delightful:enderite_knife',
  'delightful:experience_knife',
  'delightful:fiery_knife',
  'delightful:forgotten_knife',
  'delightful:froststeel_knife',
  'delightful:gilded_netherite_knife',
  'delightful:gilded_quartz_knife',
  'delightful:invar_knife',
  'delightful:ironwood_knife',
  'delightful:kiwano_knife',
  'delightful:knightmetal_knife',
  'delightful:lapis_lazuli_knife',
  'delightful:large_amethyst_knife',
  'delightful:lead_knife',
  'delightful:leaf_knife',
  'delightful:living_knife',
  'delightful:manasteel_knife',
  'delightful:mythril_knife',
  'delightful:necronium_knife',
  'delightful:netherite_opal_knife',
  'delightful:nickel_knife',
  'delightful:obsidian_infused_enderite_knife',
  'delightful:onyx_knife',
  'delightful:osmium_knife',
  'delightful:pendorite_knife',
  'delightful:refined_glowstone_knife',
  'delightful:refined_obsidian_knife',
  'delightful:rose_gold_knife',
  'delightful:sinisite_knife',
  'delightful:soul_steel_knife',
  'delightful:steeleaf_knife',
  'delightful:stellium_knife',
  'delightful:terra_knife',
  'delightful:thyrium_knife',
  'delightful:tin_knife',
  'delightful:utherium_knife',
  'delightful:warden_knife',
  'delightful:zinc_knife',
  'outer_end:cobalt_crystal_boots',
  'outer_end:cobalt_crystal_chestplate',
  'outer_end:cobalt_crystal_helmet',
  'outer_end:cobalt_crystal_leggings',
  'outer_end:mint_crystal_boots',
  'outer_end:mint_crystal_chestplate',
  'outer_end:mint_crystal_helmet',
  'outer_end:mint_crystal_leggings',
  'outer_end:rose_crystal_boots',
  'outer_end:rose_crystal_chestplate',
  'outer_end:rose_crystal_helmet',
  'outer_end:rose_crystal_leggings',
  'outer_end:sinker_dagger',
];

