const Removals = [
  '/embers:silver_axe/',
  '/embers:silver_hoe/',
  '/embers:silver_pickaxe/',
  '/embers:silver_shovel/',
  '/embers:silver_sword/',
  '/enderio:broken_spawner/',
  '/enderio:filled_soul_vial/',
  '/mekanism:creative_chemical_tank/',
  '/mekanism:creative_fluid_tank/',
  'bloodmagic:inversion_pillar_cap',
  'bloodmagic:spectral',
  'decorative_blocks:blockstate_copy_item',
  'dimstorage:dim_core',
  'dimstorage:dim_wall',
  'dimstorage:solid_dim_core',
  'eidolon:deep_lead_ore',
  'eidolon:deep_silver_ore',
  'eidolon:lead_ore',
  'eidolon:silver_ore',
  'enderio:enchanter',
  'enderio:primitive_alloy_smelter',
  'immersiveengineering:deepslate_ore_lead',
  'immersiveengineering:deepslate_ore_silver',
  'immersiveengineering:ore_lead',
  'immersiveengineering:ore_silver',
  'mekanism:cardboard_box',
  'mekanism:deepslate_lead_ore',
  'mekanism:lead_ore',
  'spawn:snail_eggs',
  'spawn:snail_shell',
  'spawn:snail_spawn_egg',
];

JEIEvents.hideItems(event => {
  Removals.forEach(x => event.hide(x));
});
